### ISSUE TITLE
BrokenPipeError: [Errno 32] Broken pipe

### ISSUE THREAD

**Issue by videetnimsarkar21** [timgaripov/swa#2]
Preparing directory '/'
Using model PreResNet110
Loading dataset CIFAR10 from '/'
Files already downloaded and verified
Files already downloaded and verified
Preparing model
SGD training
Preparing directory '/'
Using model PreResNet110
Loading dataset CIFAR10 from '/'
Files already downloaded and verified
Files already downloaded and verified
Preparing model
SGD training
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Videet\Anaconda3\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Users\Videet\Anaconda3\lib\multiprocessing\spawn.py", line 114, in _main
    prepare(preparation_data)
  File "C:\Users\Videet\Anaconda3\lib\multiprocessing\spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\Videet\Anaconda3\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "C:\Users\Videet\Anaconda3\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\Users\Videet\Anaconda3\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Users\Videet\Anaconda3\lib\runpy.py", line 85, in _run_code
Traceback (most recent call last):
    exec(code, run_globals)
  File "train.py", line 148, in <module>
  File "C:\Users\Videet\SWA\swa-master\train.py", line 148, in <module>
    train_res = utils.train_epoch(loaders['train'], model, criterion, optimizer)
    train_res = utils.train_epoch(loaders['train'], model, criterion, optimizer)
  File "C:\Users\Videet\SWA\swa-master\utils.py", line 26, in train_epoch
  File "C:\Users\Videet\SWA\swa-master\utils.py", line 26, in train_epoch
    for i, (input, target) in enumerate(loader):
    for i, (input, target) in enumerate(loader):
  File "C:\Users\Videet\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 451, in __iter__
  File "C:\Users\Videet\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 451, in __iter__
    return _DataLoaderIter(self)
  File "C:\Users\Videet\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 239, in __init__
    return _DataLoaderIter(self)
    w.start()
  File "C:\Users\Videet\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 239, in __init__
  File "C:\Users\Videet\Anaconda3\lib\multiprocessing\process.py", line 105, in start
    w.start()
    self._popen = self._Popen(self)
  File "C:\Users\Videet\Anaconda3\lib\multiprocessing\process.py", line 105, in start
  File "C:\Users\Videet\Anaconda3\lib\multiprocessing\context.py", line 223, in _Popen
    self._popen = self._Popen(self)
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\Videet\Anaconda3\lib\multiprocessing\context.py", line 223, in _Popen
  File "C:\Users\Videet\Anaconda3\lib\multiprocessing\context.py", line 322, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
    return Popen(process_obj)
  File "C:\Users\Videet\Anaconda3\lib\multiprocessing\context.py", line 322, in _Popen
  File "C:\Users\Videet\Anaconda3\lib\multiprocessing\popen_spawn_win32.py", line 65, in __init__
    return Popen(process_obj)
    reduction.dump(process_obj, to_child)
  File "C:\Users\Videet\Anaconda3\lib\multiprocessing\reduction.py", line 60, in dump
  File "C:\Users\Videet\Anaconda3\lib\multiprocessing\popen_spawn_win32.py", line 33, in __init__
    ForkingPickler(file, protocol).dump(obj)
    prep_data = spawn.get_preparation_data(process_obj._name)
BrokenPipeError: [Errno 32] Broken pipe
  File "C:\Users\Videet\Anaconda3\lib\multiprocessing\spawn.py", line 143, in get_preparation_data
    _check_not_importing_main()
  File "C:\Users\Videet\Anaconda3\lib\multiprocessing\spawn.py", line 136, in _check_not_importing_main
    is not going to be frozen to produce an executable.''')
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.

**Comment by izmailovpavel** [comment]
It looks like your error is not related to our SWA code. It happens inside a dataloader. I think you should try to make a minimal reproducible example of this error and create an issue in the PyTorch repo.

**Comment by 5059** [comment]
I came across the BrokenPipeError, when I tried to run on cpu. I  change num_workers to 0, it runs.
